### PR TITLE
add python 3 support for kodi 19+

### PR DESCRIPTION
**Pull request by ilikenwf**
I have tested and it appears to work with these minute changes.

Thanks for the great addon!

### CODE REVIEW

**Comment by iticory** [comment]
It looks like you accidentally set addon.xml to 2.0.0 instead of 3.0.0.  Thanks for fixing this.  I just updated kodi today and was disappointed to see this plugin wasn't working. ;)

**Comment by petegallagher** [comment]
Thanks for the contribution, I will get this tested and merged today.

**Comment by petegallagher** [comment]
Upstream PR: https://github.com/xbmc/repo-plugins/pull/3549

**Comment by iticory** [comment]
> Upstream PR: [xbmc/repo-plugins#3549](https://github.com/xbmc/repo-plugins/pull/3549)

FYI... A couple minor changes are being requested by the upstream :)

**Pull request merged**
